<?php 

//session_cache_limiter('nocache');

//session_start();

include("scripts/settings.php"); 

if(!logvalidate('user')){

	header('Location: login.php');

}



if(isset($_GET['id'])){

	$sql_invoice1 = 'select * from form_fee where sno="'.$_GET['id'].'"';

	$inv_id=mysqli_fetch_array(execute_query(connect(), $sql_invoice1));

  $class_description = '';

  if ($inv_id['class'] == "phd_commerce") {

    $class_description = "PHD COMMERCE";

  }

  elseif ($inv_id['class'] == "phd_education") {

    $class_description = "PHD EDUCATION";

  }

  elseif ($inv_id['class'] == "phd_english") {

    $class_description = "PHD ENGLISH";

  }

  elseif ($inv_id['class'] == "phd_zoology") {

    $class_description = "PHD ZOOLOGY";

  }

  else{

    $sql_class = 'SELECT * FROM `class_detail`  WHERE `sno`="'.$inv_id['class'].'"';

    $result_class = execute_query(connect(), $sql_class );

    $row_class = mysqli_fetch_array($result_class);

    $class_description = $row_class['class_description'];

  }

  if($inv_id['fee_submission_type'] == "Admission Form"){

    $fee_type = 'ADM';

  }

  else if($inv_id['fee_submission_type'] == "Duplicate Form"){

    $fee_type = 'DUP';

  }

  else if($inv_id['fee_submission_type'] == "tc_cc"){

    $fee_type = 'TCCC';

  }

  else if($inv_id['fee_submission_type'] == "miscellaneous"){

    $fee_type = 'MIS';

  }

  if ($inv_id['created_by'] != '') {

    $sql_user = 'SELECT * FROM `user` WHERE `userid`="'.$inv_id['created_by'].'"';

    $result_user = execute_query(connect(), $sql_user );

    $row_user = mysqli_fetch_array($result_user);

  }

}



?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href="pop.css" TYPE="text/css" REL="stylesheet" media="all">

<style type="text/css">

@media print {

input#btnPrint {

display: none;

	}	

}

table, tr, td {font-size:14px; border:none; font-weight:bold;}

h3{ font-size:16px;}

</style>

<script language="javascript" type="text/javascript">

//window.print();

</script>

</head>

<body>

	<div><input type="button" id="btnPrint" onclick="window.print();" value="Print Page" /></div>

	<div id="newdiv" style="page-break-after:avoid; margin-bottom:50px;">

     <h5 style="text-align:center; text-decoration:underline;">Student Copy</h5>

    <div style="text-align: center;padding-top: 5px;"><b><u><?php echo $inv_id['fee_submission_type']; ?></u></b></div>

        <table border="1">

        	<tr>

            	<td align="right" style="width:150px;"><img src="images/clogo.gif" style="height:60px;"></td>

                <?php 

						echo' <td align="left"><h3 style="text-align:center">Kamla Nehru Institute Of Physical & Social Sciences<br>Sultanpur - 228118(U.P.)</h3>                         </td>';

					?>

            </tr>

        </table>

		<div style="margin:15px 0px 0px 20px;">

			<table >  

			 <tr>

          <td>Receipt Number: <b><?php echo mysqli_fetch_array(execute_query(connect(),"SELECT * FROM `general_settings` WHERE `description`='session'"))['value'].'/'.$fee_type.'&nbsp;'.$inv_id['receipt_number']; ?></b></td>

          <td>Receipt generated on <b><?php echo date('d-m-Y' , strtotime($inv_id['fee_submission_date']));?></b></td>
			<td>&nbsp;</td>
				<td><B>Batch:</B></td><td><?php echo $inv_id['batch']; ?></td>
        </tr>

        <?php 

          if($inv_id['created_by'] != ''){

            echo '<tr><td></td><td>Generated By: '.$row_user['username'].'</td></tr>';

          }

        ?>

			</table>

			<table width="70%">

              <?php if($inv_id['form_no'] != ''){ ?>

              <tr><td><b>Form No.:</b></td><td><?php echo $inv_id['form_no']; ?></td></tr>

              <?php } ?>

              <tr><td><b>Name:</b></td><td><?php echo $inv_id['stu_name'];?></td></tr>

              <?php if($inv_id['father_name'] != ''){ ?>

              <tr><td><b>Father's Name:</b></td><td> <?php echo $inv_id['father_name'];?></td></tr>

              <?php } ?>

              <?php if($inv_id['dob'] != ''){ ?>

              <tr><td><b>DOB: </b></td><td><?php echo $inv_id['dob'];?></td></tr>

              <?php } ?>

              <tr><td><b>Category: </b></td><td><?php echo $inv_id['category'];?></td></tr>

              <tr><td><b>Class:</b></td><td><?php echo $class_description;?></td></tr>

              <?php if($inv_id['sub1'] != ''){ ?>

              <tr><td><b>Subjects:</b></td><td><?php echo $inv_id['sub1'];?></td></tr>

              <?php } ?>
				
              <tr><td><B>Fees Amount:</B></td><td>Rs.<?php echo $inv_id['amount']; ?></td></tr>

              <tr><td>&nbsp;</td></tr>

			</table>

		</div>

		<div style="float:right; padding-right:20px;margin-top:-15px;"><b>(Cashier's Signature)</b></div>

	</div>

    

	<div id="newdiv" style="page-break-after:always; margin-bottom:50px;">

        <h5 style="text-align:center; text-decoration:underline;">College Copy</h5>

        <div style="text-align: center;padding-top: 5px;"><b><u><?php echo $inv_id['fee_submission_type']; ?></u></b></div>

        <table border="1">

        	<tr>

            	<td align="right" style="width:150px;"><img src="images/clogo.gif" style="height:60px;"></td>

                <?php 

						echo' <td align="left"><h3 style="text-align:center">Kamla Nehru Institute Of Physical & Social Sciences<br>Sultanpur - 228118(U.P.)</h3>                         </td>';

					?>

            </tr>

        </table>

        <div style="margin:15px 0px 0px 20px;">

            <table >  

                <tr>

                  <td>Receipt Number: <b><?php echo mysqli_fetch_array(execute_query(connect(),"SELECT * FROM `general_settings` WHERE `description`='session'"))['value'].'/'.$fee_type.'&nbsp;'.$inv_id['receipt_number']; ?></b></td>

                  <td>Receipt generated on <b><?php echo date('d-m-Y' , strtotime($inv_id['fee_submission_date']));?>

                </b></td>
				<td>&nbsp;</td>
				<td><B>Batch:</B></td><td><?php echo $inv_id['batch']; ?></td>

                </tr>

                <?php 

                  if($inv_id['created_by'] != ''){

                    echo '<tr><td></td><td>Generated By: '.$row_user['username'].'</td></tr>';

                  }

                ?> 

            </table>

            <table width="70%">

              <?php if($inv_id['form_no'] != ''){ ?>

              <tr><td><b>Form No.:</b></td><td><?php echo $inv_id['form_no']; ?></td></tr>

              <?php } ?>

              <tr><td><b>Name:</b></td><td><?php echo $inv_id['stu_name'];?></td></tr>

              <?php if($inv_id['father_name'] != ''){ ?>

              <tr><td><b>Father's Name:</b></td><td> <?php echo $inv_id['father_name'];?></td></tr>

              <?php } ?>

              <?php if($inv_id['dob'] != ''){ ?>

              <tr><td><b>DOB: </b></td><td><?php echo $inv_id['dob'];?></td></tr>

              <?php } ?>

              <tr><td><b>Category: </b></td><td><?php echo $inv_id['category'];?></td></tr>

              <tr><td><b>Class:</b></td><td><?php echo $class_description;?></td></tr>

              <?php if($inv_id['sub1'] != ''){ ?>

              <tr><td><b>Subjects:</b></td><td><?php echo $inv_id['sub1'];?></td></tr>

              <?php } ?>
			  
              <tr><td><B>Fees Amount:</B></td><td>Rs.<?php echo $inv_id['amount']; ?></td></tr>

              <tr><td>&nbsp;</td></tr>

            </table>

        </div>

        <div style="float:right; padding-right:20px;"><b>(Cashier's Signature)</b>

        </div>

    </div>

 <div><input type="button" id="btnPrint" onclick="window.print();" value="Print Page" /></div>

</body>

</html>